Algoritmo "RESPOSTA EXERCÍCIO 02"
// Autor(a)    : Guilherme Castilho
// Data atual  : 08/08/2020
Var
   N1, N2:inteiro
   
Inicio
      ESCREVAL ("Identificando o Maior ou Menor número")
      ESCREVAL("Dígite o primeiro número: ")
      LEIA (N1)
      ESCREVAL ("Dígite o segundo número: ")
      LEIA (N2)
      SE (N1>=N2) E (N2<=N1) ENTAO
      ESCREVAL ("O maior número foi: ", N1)
      SENAO
      ESCREVAL("E o menor número foi : ",N1)
      FIMSE


      




Fimalgoritmo
