Algoritmo "BART"
// 
//  
// Descrição   : ESTRUTURA DE RPETIÇÃO
// Autor(a)    : Gui Castilho
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
   Nome:caracter
   B:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("Bart Simpsons, digite PROA4.0 mil vezes")
   leia(nome)
    Para B<- 1 ate 1000 faca
     escreval ("PROA4.0")
      Fimpara

Fimalgoritmo