Algoritmo "RESPOSTA 08)
// Autor(a)    : Gui Castilho
// Data atual  : 07/08/2020
Var

nome:caracter
idade:inteiro
media ,nascimento:inteiro

Inicio

escreval("Digite seu nome")
leia(nome)
escreval("Digite sua idade")
leia(idade)

se idade >=18 entao
se idade >=65 entao
escreval(nome," Você é maior de idade e por isso ainda é idoso")
senao
escreval(nome," Você é maior de idade e ainda não é idoso")
fimse
senao
escreval(nome," Você ainda é menor de idade")
fimse


     

Fimalgoritmo