Algoritmo "Resposta 13"

Var
   vet:vetor[1..10] de inteiro
    contadora:inteiro
     Num:inteiro

Inicio
  Escreval("Dígite 10 números:")
   para contadora de 1 ate 10 faca
    Leia(NuM)
    vet[contadora] <-Num
     fimpara
      vet[contadora] <-num
      Escreval("Portanto a ordem digitada é:")
      para contadora de 1 ate 10 faca
       escreva(vet[contadora])
       fimpara
       






Fimalgoritmo