Algoritmo "RESPOSTA 06"

// Autor(a)    : Gui Castilho
// Data atual  : 09/08/2020
var
   KM, MS, HR, RJSP: real

inicio
      Escreval ("Dígite a sua Kilometragem : ")
      LEIA (KM)
      MS <- KM * 1000
      Escreval (" Em M/s seu veículo converte em : ")
      Escreval ( MS , " M/s ")
      Escreval (" Informe KM tem de distância entre SP e RJ: ")
      LEIA (RJSP)
      HR <-
      Escreval ("O tempo médio de percurso estima-se em: " , HR)




fimalgoritmo